kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ubi-builder-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
  volumeMode: Filesystem
