apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: GIT_PROJECT_URL
      description: The git repository url (e.g. http://github.com/myorg/myrepo.git)
      type: string
  workspaces:
    - name: source-dir
      description: A workspace for the task
      optional: true
      mountPath: /mnt/workspace
  steps:
    - name: clone
      image: quay.io/redhat-cop/ubi8-git:v1.0
      workingDir: $(workspaces.source-dir.path)
      command:
        - sh
        - -c
      args:
        - git clone $(params.GIT_PROJECT_URL) .
