---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pack-build-builder-push
  labels:
    app.kubernetes.io/version: '0.1'
  annotations:
    tekton.dev/pipelines.minVersion: '0.50.0'
    tekton.dev/tags: build, push, builder
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This Pipeline builds a buildpacks builder image using pack client.
  workspaces:
    - name: source-dir
    - name: data-store
    - name: pack-workspace
  params:
    - name: gitUbiBuilderUrl
      type: string
      description: Url of the git project containing the ubi builder imageproject
      default: ""
    - name: imageUrl
      type: string
      description: Pack image url
      default: buildpacksio/pack
    - name: imageTag
      type: string
      description: Pack image tag
      default: latest
    - name: packCmdBuilderArgs
      type: array
      description: Pack command and arguments to execute
      default: [""]

  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: GIT_PROJECT_URL
          value: '$(params.gitUbiBuilderUrl)'
      workspaces:
        - name: source-dir
          workspace: source-dir

    #- # Enable Experimental Pack Features
    #  name: pack-enable-experimental
    #  runAfter:
    #    - git-clone
    #  taskRef:
    #    name: pack
    #  params:
    #    - name: PACK_IMAGE
    #      value: '$(params.imageUrl)'
    #    - name: PACK_VERSION
    #      value: '$(params.imageTag)'
    #    - name: PACK_ARGS
    #      value:
    #        - config
    #        - experimental
    #        - "true"
    #  workspaces:
    #    - name: source-dir
    #      workspace: source-dir

    - name: fetch-pack-config
      runAfter:
        - git-clone
      taskSpec:
        steps:
          - image: quay.io/centos/centos:latest
            script: |
              echo "Copy pack config.toml to $(workspaces.pack-workspace.path)"
              cp $(workspaces.data-store.path)/config.toml $(workspaces.pack-workspace.path)
      workspaces:
        - name: data-store
          workspace: data-store
        - name: pack-workspace
          workspace: pack-workspace

    - name: list-files
      runAfter:
        - fetch-pack-config
      taskSpec:
        steps:
          - image: quay.io/centos/centos:latest
            script: |
              echo "List files under $(workspaces.pack-workspace.path)"
              ls -la $(workspaces.pack-workspace.path)/
              
              echo "List files under $(workspaces.source-dir.path)"
              ls -la $(workspaces.source-dir.path)/
      workspaces:
        - name: pack-workspace
          workspace: pack-workspace
        - name: source-dir
          workspace: source-dir

    - name: pack
      runAfter:
        - fetch-pack-config
      taskRef:
        name: pack
      params:
        - name: PACK_IMAGE
          value: '$(params.imageUrl)'
        - name: PACK_VERSION
          value: '$(params.imageTag)'
        - name: PACK_ARGS
          value: ["$(params.packCmdBuilderArgs)"]
      workspaces:
        - name: source-dir
          workspace: source-dir
        - name: pack-workspace
          workspace: pack-workspace
