---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pack-build-builder-push-run
spec:
  pipelineRef:
    name: pack-build-builder-push
  workspaces:
    - name: source-dir
      persistentVolumeClaim:
        claimName: ubi-builder-vol
  params:
    - name: packCmd
      value: "builder create builder --config ubi-builder.toml"
    - name: gitProjectUrl
      value: https://github.com/redhat-buildpacks/ubi-image-builder.git