---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pack-build-builder-push-run
spec:
  #serviceAccountName: buildpacks
  pipelineRef:
    name: pack-build-builder-push
  params:
    - name: gitUbiBuilderUrl
      value: https://github.com/redhat-buildpacks/ubi-image-builder.git
    - name: packCmdBuilderArgs
      value:
      - builder
      - create
      - -v
      - quay.io/snowdrop/ubi-builder
      - --config
      - ubi-builder.toml
      - --publish

  workspaces:
    - name: source-dir
      persistentVolumeClaim:
        claimName: ubi-builder-vol
    - name: pack-workspace
      persistentVolumeClaim:
        claimName: pack-workspace-vol
    - name: data-store
      projected:
        sources:
          - secret:
              name: pack-config-toml
          - secret:
              name: quay-creds
