---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pack-build-builder-push-run
spec:
  pipelineRef:
    name: pack-build-builder-push
  workspaces:
    - name: source-dir
      persistentVolumeClaim:
        claimName: ubi-builder-vol
    - name: pack-config-toml
      configMap:
        name: pack-config-toml
  params:
    - name: packCmdBuilderArgs
      value:
      - builder
      - create
      - -v
      - quay.io/swowdrop/ubi-builder
      - --config
      - ubi-builder.toml

    - name: gitUbiBuilderUrl
      value: https://github.com/redhat-buildpacks/ubi-image-builder.git