---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pack-build-builder-push
  labels:
    app.kubernetes.io/version: '0.1'
  annotations:
    tekton.dev/pipelines.minVersion: '0.50.0'
    tekton.dev/tags: build, push, builder
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This Pipeline builds a buildpacks builder image using pack client.
  workspaces:
    - name: source-dir
    - name: data-store
    - name: pack-workspace
  params:
    - description: A boolean value used to execute or not a task
      default: "false"
      name: debug
    - name: gitUbiBuilderUrl
      type: string
      description: Url of the git project containing the ubi builder imageproject
      default: ""
    - description: Source directory where code is cloned
      name: source-dir
      default: "."
      type: string
    - name: imageUrl
      type: string
      description: Pack image url
      default: buildpacksio/pack
    - name: imageTag
      type: string
      description: Pack image tag
      default: latest
    - name: packCmdBuilderArgs
      type: array
      description: Pack command and arguments to execute
      default: [""]

  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: GIT_PROJECT_URL
          value: '$(params.gitUbiBuilderUrl)'
      workspaces:
        - name: source-dir
          workspace: source-dir

    - name: fetch-packconfig-registrysecret
      runAfter:
        - git-clone
      taskSpec:
        steps:
          - image: quay.io/centos/centos:latest
            script: |
              echo "Copy pack config.toml to $(workspaces.pack-workspace.path)"
              cp $(workspaces.data-store.path)/config.toml $(workspaces.pack-workspace.path)
              
              echo "Copy .dockerconfigjson to $(workspaces.pack-workspace.path)/.docker/config.json"
              mkdir -p $(workspaces.pack-workspace.path)/.docker
              cp $(workspaces.data-store.path)/.dockerconfigjson $(workspaces.pack-workspace.path)/.docker/config.json
      workspaces:
        - name: data-store
          workspace: data-store
        - name: pack-workspace
          workspace: pack-workspace

    - name: list-files
      runAfter:
        - fetch-packconfig-registrysecret
      when:
        - input: $(params.debug)
          operator: in
          values: [ "true" ]
      taskSpec:
        steps:
          - name: list-source-workspace
            image: quay.io/centos/centos:latest
            script: |
              echo "List files under: $(workspaces.pack-workspace.path)"
              ls -la $(workspaces.pack-workspace.path)/
              
              ls -la $(workspaces.pack-workspace.path)/.docker/
              
              cat $(workspaces.pack-workspace.path)/.docker/config.json
              
              echo "List files under: $(workspaces.source-dir.path)"
              ls -la $(workspaces.source-dir.path)/
      workspaces:
        - name: pack-workspace
          workspace: pack-workspace
        - name: source-dir
          workspace: source-dir

    - name: pack
      runAfter:
        - fetch-packconfig-registrysecret
      taskRef:
        resolver: git
        params:
        - name: url
          value: https://github.com/redhat-buildpacks/ubi-image-builder.git
        - name: revision
          value: main
        - name: pathInRepo
          value: /tekton/task/pack/0.1/pack-builder.yml
      params:
        - name: PACK_IMAGE
          value: '$(params.imageUrl)'
        - name: PACK_VERSION
          value: '$(params.imageTag)'
        - name: PACK_ARGS
          value: ["$(params.packCmdBuilderArgs)"]
      workspaces:
        - name: source-dir
          workspace: source-dir
        - name: pack-workspace
          workspace: pack-workspace
