kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pack-workspace-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
  volumeMode: Filesystem
